name: Add label

on:
  workflow_dispatch:
    inputs:
      label_name:
        decription: Label name
        required: true
        type: string

jobs:
  add-label:
    name: Add label
    runs-on: ubuntu-latest
    env:
      DB_NAME: lofi.db
      DRIVE_DB_FILE: lofi.db
      GOOGLE_API_TOKEN: ${{ secrets.GOOGLE_API_TOKEN }}
      NEW_LOFI_PLAYLIST_ID: 4FDJIsW0avzmwWxpX67c4h
      SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIPY_REDIRECT_URI: http://localhost:8080
      SPOTIFY_USER_ID: 1175574971

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .

      - name: Create Google API token cache
        run: echo "$GOOGLE_API_TOKEN" >> google_api_token.json

      - name: Download database
        run: lofi db download

      - name: Add label
        run: lofi add-label --name="${{ inputs.label_name }}"

      - name: Upload database
        run: lofi db upload

      - name: Store Google token cache into secret
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_TO_SET_SECRETS }}
        run: gh secret set GOOGLE_WMF_TOOLS_API_TOKEN < google_api_token.json
